server:
  port : 8083
  servlet:
    session:
      timeout: 1800
      
spring:
  application:
    name: LongBlack
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: longblack.help
    password: tktrcxgygwrmugdi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000
  h2:
    console:
      enabled: true
      path: /h2-console
  
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: true
        
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalababbbaaaaaaaaaabbbbb

logging:
  level:
    '[org.springframework]': debug
    
symmetric:
  key: 3o3Test!@#!11
  salt: 70726574657374
